{{- range $key, $svc := .Values.services }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $svc.name }}
  namespace: {{ $.Values.global.namespace }}
  labels:
    app: {{ $svc.name }}
    version: {{ $.Values.global.imageTag }}
spec:
  replicas: {{ $svc.replicas }}
  selector:
    matchLabels:
      app: {{ $svc.name }}
  template:
    metadata:
      labels:
        app: {{ $svc.name }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: {{ $svc.port | quote }}
    spec:
      containers:
        - name: {{ $svc.name }}
          image: "{{ $.Values.global.imageRegistry }}/{{ $svc.image }}:{{ $.Values.global.imageTag }}"
          ports:
            - containerPort: {{ $svc.port }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: "{{ $.Values.keycloakUrl }}/realms/{{ $.Values.realmName }}"
          resources:
            requests:
              cpu: {{ $svc.resources.requests.cpu }}
              memory: {{ $svc.resources.requests.memory }}
            limits:
              cpu: {{ $svc.resources.limits.cpu }}
              memory: {{ $svc.resources.limits.memory }}
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{ $svc.port }}
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: {{ $svc.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
  {{- end }}