# Les microservices acceptent uniquement le trafic depuis l'api-gateway
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-gateway-to-services
  namespace: {{ .Values.global.namespace }}
spec:
  podSelector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - incident-service
          - notification-service
          - reporting-service
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: api-gateway
---
# L'api-gateway accepte uniquement le trafic depuis l'Ingress NGINX
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-to-gateway
  namespace: {{ .Values.global.namespace }}
spec:
  podSelector:
    matchLabels:
      app: api-gateway
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx