name: PR Validation

on:
  pull_request:
    branches: [main, develop]

jobs:
  validate:
    name: Validate PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: temurin
          cache: maven

      - name: Build & test
        run: mvn clean verify -B --no-transfer-progress

      - name: Helm lint
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
          helm lint helm/cloudops-app
          helm lint helm/keycloak || true

      - name: Terraform validate
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Terraform fmt check
        run: |
          cd terraform
          terraform fmt -check -recursive